baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
enableEmoji = true

theme = "prospace"

[markup.goldmark.renderer]
unsafe= true
[params]
#color = "#5da87e"
color = "black"

[params.footer]
prospace = "A PROSPACE marca presenÃ§a no mercado portuguÃªs e africano, privilegiando os paÃ­ses de expressÃ£o oficial portuguesa, paÃ­ses mais prÃ³ximos e com uma cultura partilhada, com necessidades particulares e desafios concretos."
member = [["â¡ï¸ APMI", "https://www.apmi.pt"]]
presence = ["â­ Portugal", "â­ Angola", "â­ MonÃ§ambique", "â­ SÃ£o TomÃ© e PrÃ­ncipe"]
contacts =[ "âœ‰ï¸ geral@prospace.pt", "ğŸ“ +351 210 990 079", "ğŸ¢ R. Latino Coelho, 87, Sala 22/23", "1050-134 Lisboa, Portugal"]